---
version: "3"
services:
  registrar:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: ./docker/env_file
    volumes:
      - database:/app/data/
    ports:
      - 80:80

volumes:
  database:
