---
version: "3"
services:
  registrar:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: ./docker/env_file
    volumes:
      - database:data/sqlite.db

volumes:
  database: